version: '3'

services:
  # api:
  #   container_name: music-service
  #   build: .
  #   restart: always
  #   ports:
  #     - ${PORT}:${PORT}
  #     - 9229:9229
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   command: yarn start:docker
  #   depends_on:
  #     - postgres
  #   environment:
  #     PORT: 8000
  #   networks:
  #     - postgres

  postgres:
    container_name: pg_db
    image: postgres:14-alpine
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - /data/postgres:/data/postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8081:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    environment:
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - postgres
    tty: true

networks:
  postgres:
    driver: bridge
